# Generated by Django 3.0.3 on 2020-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200205_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
