# Generated by Django 3.0.3 on 2020-02-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_room_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='z',
        ),
    ]
